spring:
  application:
    name: Cards     # Apparently this needs to be the same case as the .yml filename in the configserver. Else it fails. Since configserver reads from local filesystem now, the OS does a case-insensitive match at the file level. But might fail in prod on a Linux container.
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: "prod"
  config:
    import: "configserver:http://localhost:8071/"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 9000

build:
  version: "1.0"

cards:
  message: "Welcome to Cards service of DemoBank!"
  contactInfo:
    name: "Jane Doe"
    email: "jane@demobank.com"
  onCallSupport:
    - (555) 555-4321
    - (555) 512-8765

management:
  endpoints:
    web:
      exposure:
        include: "*"
