services:
  accounts:
    image: "demobank/accounts"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - demobank

  cards:
    image: "demobank/cards"
    container_name: "cards-ms"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - demobank

  loans:
    image: "demobank/loans"
    container_name: "loans-ms"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - demobank

networks:
  demobank:
    driver: "bridge"