spring:
  application:
    name: gatewayserver
  config:
    import: optional:configserver:http://localhost:8071/
  cloud:                  # enabling GatewayServer to create routes based on services registered in a
    gateway:              # DiscoveryClient compatible service registry implementation (Netflix Eureka here)
      server:             # property is spring.cloud.gateway.server.webflux.discovery.locator=true
        webflux:          # and not what is in Spring Cloud Gateway 5.0.3 docs
          discovery:      # the routes for services are available at http://localhot:8072/actuator/gateway/routes
            locator:      # API calls to services via gateway can be made at http://localhost:8072/service-name/api-path
              enabled: true      # ex 'http://localhost:8072/ACCOUNTS/api/create'. Service names are same as seen in Eureka dashboard
              lowerCaseServiceId: true      # property to enable lower case service names in API URI
          httpclient:                  # add property to gateway server to configure global Http timeouts.
            connect-timeout: 1000      # the prefix for properties in Spring Cloud Gateway using reactive WebFlux
            response-timeout: 5s       # is spring.cloud.gateway.server.webflux.* and not the spring.cloud.gateway.*
                                       # as seen in official docs. This is a rollout gap.
#          default-filters:            # this is how CircuitBreaker and Retry would be implemented in the GatewayServer
#            - name: CircuitBreaker    # on the whole without the use of custom route config via RouteLocator bean in main app
#              args:                   # default-filters gets applied to every route, including auto-generated ones.
#                name: defaultCircuitBreaker
#                fallbackUri: forward:/contactSupport
#            - name: Retry             # one downside is that all services share a common CB called defaultCircuitBreaker
#              args:                   # so if one service fails and circuit opens, the other service calls will
#                retries: 3            # get the fallback too. Per service breakers can be iplemented in the YAML
#                methods: GET          # with 'routes' property. It can be passed a list of routes with their own props each.
#                backoff:
#                  firstBackoff: 100ms
#                  maxBackoff: 1000ms
#                  factor: 2
#                  basedOnPreviousValue: true

info:
  app:
    name: gatewayserver
    description: Gateway server of Demo Bank application
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:                  # enable actuator endpoint to monitor and interact with Spring Cloud Gateway project
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

# maintaining EurekaServer related properties in the ConfigServer

# enable logging level for DEBUG for all code in com.demobank.gatewayserver package to be visible on console
logging:
  level:
    com:
      demobank:
        gatewayserver: DEBUG

# configure property values for Resilience4J Spring Cloud Circuit Breaker
resilience4j.circuitbreaker:
  configs:
    default:                                    # default values for all circuit breakers. Can change this to a named circuit breaker
      slidingWindowSize: 10                     # consider this many requests at a time to make a decision based on threashold
      permittedNumberOfCallsInHalfOpenState: 2  # number of calls/requests sent to closed service when in half-open state to check if recovered or not
      failureRateThreshold: 50                  # threshold in % for failure rate of calls to transition circuit state
      waitDurationInOpenState: 10000            # duration circuit waits in open state before transitioning to half-open