spring:
  application:
    name: gatewayserver
  config:
    import: optional:configserver:http://localhost:8071/
  cloud:                  # enabling GatewayServer to create routes based on services registered in a
    gateway:              # DiscoveryClient compatible service registry implementation (Netflix Eureka here)
      server:             # property is spring.cloud.gateway.server.webflux.discovery.locator=true
        webflux:          # and not what is in Spring Cloud Gateway 5.0.3 docs
          discovery:      # the routes for services are available at http://localhot:8072/actuator/gateway/routes
            locator:      # API calls to services via gateway can be made at http://localhost:8072/service-name/api-path
              enabled: true      # ex 'http://localhost:8072/ACCOUNTS/api/create'. Service names are same as seen in Eureka dashboard
              lowerCaseServiceId: true      # property to enable lower case service names in API URI

info:
  app:
    name: gatewayserver
    description: Gateway server of Demo Bank application
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:                  # enable actuator endpoint to monitor and interact with Spring Cloud Gateway project
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

# maintaining EurekaServer related properties in the ConfigServer

# enable logging level for DEBUG for all code in com.demobank.gatewayserver package to be visible on console
logging:
  level:
    com:
      demobank:
        gatewayserver: DEBUG