spring:
  application:
    name: Loans
  datasource:
    url: jdbc:mysql://localhost:3308/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"

server:
  port: 8090

build:
  version: "1.0"

loans:
  message: "Welcome to Loans service of DemoBank"
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@demobank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934

management:
  endpoints:
    web:
      exposure:
        include: "*"