spring:
  application:
    name: Loans
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: "prod"
  config:
    import: "configserver:http://localhost:8071/"

server:
  port: 8090

build:
  version: "1.0"

loans:
  message: "Welcome to Loans service of DemoBank"
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@demobank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934

management:
  endpoints:
    web:
      exposure:
        include: "*"