# adding a separate docker compose file for each profile to handle running of configserver + services for that profile.
services:
  redis: # add a service for Redis datastore container. For Redis request rateLimiter
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL","redis-cli ping | grep PONG" ]
      timeout: 10s
      retries: 10
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver: # adding configserver as a service with the same name to run in the
    image: "demobank/configserver:s6"   # network 'demobank' to allow the containers to communicate with each other
    container_name: "configserver-ms"   # by name since each container has its own isolated namespace/loopback
    ports: # for 'localhost'. If accounts container is running outside a network,
      - "8071:8071"                     # it won't be able to find configserver at localhost:8071 since accounts
      # container has its own 'localhost' and nothing is listening on 8071.


    healthcheck: # add a health check with instruction on what to test for. This one checks for readiness of configserver container
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s           # instruct the health check to start only 10s after the container starts, to perform
      retries: 10             # up to 10 retries, with an interval of 10s between each. If the check takes longer
      timeout: 5s             # than 5s from the time it started, it is considered to have failed.
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "demobank/eurekaserver:s8"
    container_name: "eurekaserver-ms"
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      retries: 10
      timeout: 5s
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  accounts:
    image: "demobank/accounts:s10"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      retries: 10
      timeout: 5s
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  cards:
    image: "demobank/cards:s9"
    container_name: "cards-ms"
    ports:
      - "9000:9000"
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      retries: 10
      timeout: 5s
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: cards
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  loans:
    image: "demobank/loans:s9"
    container_name: "loans-ms"
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      retries: 10
      timeout: 5s
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: loans
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  gatewayserver:
    image: "demobank/gatewayserver:s10"
    container_name: "gatewayserver-ms"
    ports:
      - "8072:8072"
    depends_on:
      accounts:
        condition: service_healthy
      cards:
        condition: service_healthy
      loans:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
     SPRING_DATA_REDIS_HOST: redis
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

networks:
  demobank:
    driver: "bridge"