# adding a separate docker compose file for each profile to handle running of configserver + services for that profile.
services:
  accountsdb:                            # creating a service for the new MySQL container for Accounts service and so on
    container_name: accountsdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    container_name: cardsdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    container_name: loansdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:                         # adding configserver as a service with the same name to run in the
    image: "demobank/configserver:s6"   # network 'demobank' to allow the containers to communicate with each other
    container_name: "configserver-ms"   # by name since each container has its own isolated namespace/loopback
    ports:                              # for 'localhost'. If accounts container is running outside a network,
      - "8071:8071"                     # it won't be able to find configserver at localhost:8071 since accounts
                                        # container has its own 'localhost' and nothing is listening on 8071.

    healthcheck:              # add a health check with instruction on what to test for. This one checks for readiness of configserver container
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s           # instruct the health check to start only 10s after the container starts, to perform
      retries: 10             # up to 10 retries, with an interval of 10s between each. If the check takes longer
      timeout: 5s             # than 5s from the time it started, it is considered to have failed.
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "demobank/accounts:s7"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    environment:                       # defining environment variables to allow comms with configserver as mentioned above
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    depends_on:
      configserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "demobank/cards:s7"
    container_name: "cards-ms"
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    depends_on:
      configserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "demobank/loans:s7"
    container_name: "loans-ms"
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  demobank:
    driver: "bridge"