build:
  version: "3.0"

accounts:
  message: "Welcome to Accounts Production service of DemoBank! Testing Spring Cloud Bus"
  contactInfo:
    name: "Ren Ash - Product owner"
    email: "ren@demobank.com"
  onCallSupport:
    - (456) 455-1234
    - (456) 412-5678
