# changed application.properties to application.yml (YAML file)

server:
  port: 8080

spring:
  application:
    name: accounts
  datasource:               # reverting to in-memory H2 database from MySQL running in containers to reduce number of containers
    url: jdbc:h2:mem:testdb
    driverClassname: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:             # tell Spring which profile to activate. The name is derived and know to Spring
    active: "prod"        # since the convention of 'application-{profileName}' was followed. Now it takes from configserver.
 # config:                This property tells Spring to import the values in the files specified. This is needed
 #   import:                        in case the naming convention of "application-{profile}" is not followed.
 #     - "application_qa.yml"       Spring ignores .properties/yml files that do not follow the convention other
 #     - "application_prod.yml"     than the default file.
  config:
    import: "optional:configserver:http://localhost:8071/"  # adding 'optional' since this value does not get overridden when another value is passed as an environment variable. Apparently this one property in spring does not use the highest precedence value, but evaluates are values for spring.config.import. Since this is running in a container, it cannot reach configserver via localhost hence optional.
      # telling accounts service to import configs from the configserver
                                                   # at that location. The string 'configserver' is mandatory here irrespective of server application name.
#  rabbitmq:              # define broker credentials for RabbitMQ (container running on port 5672) to use. Commenting out since not used going forward.
#    host: localhost      # 'busrefresh' endpoint of actuator for Spring Cloud Bus. These are default values
#    port: 5672           # and do not need to be mentioned explicitly since Spring Cloud is already configured
#    username: guest      # Instead of invoking 'actuator/refresh' for each service, 'actuator/busrefresh' can
#    password: guest      # be invoked for one service and all nodes registered with MQ will refresh configs from configserver
                         # via Spring Cloud Bus

build:
  version: "1.0"

# adding some properties with the prefix 'accounts' to demonstrate @ConfigurationProperties of Spring Boot to inject
# external values at runtime. Here 'message' is a String value. 'contactInfo' is a Map of <String, String> values,
# and 'onCallSupport' is a List of <String> values.

accounts:
  message: "Welcome to Accounts service of DemoBank!"
  contactInfo:
    name: "John Doe"
    email: "john@demobank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 512-5678

# expose all management related endpoints support by Spring Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted    # enable endpoint to let the application be gracefully shutdown.
  info:
    env:
      enabled: true           # enable exposure of environment properties through Spring Boot Actuator's info endpoint

# properties for Eureka Server interaction as a Client
eureka:
  instance:
    preferIpAddress: true      # Using IP address of each service in the Eureka Server instead of DNS name since there is no DNS mapping in the local system
  client:
    fetchRegistry: true        # Fetch registry details from Eureka Server on startup
    registerWithEureka: true   # Register the service with Eureka Server on startup
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

# some properties that are displayed in the Eureka Server dashboard (localhost:8070/) for this service
info:
  app:
    name: accounts
    description: Accounts service of Demo Bank application
    version: 1.0.0