# changed application.properties to application.yml (YAML file)

server:
  port: 8080

spring:
  application:
    name: accounts
  datasource:               # to update this with MySQL for each service running in a container. Created by ' docker run -p 3306:3306 --name accountsdb -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=accountsdb -d mysql '. replace first 3306 with 7 and 8 for other services, container name with --name, and database name being passed via environment vriable with -e. Interact via SQLectron Client.
    url: jdbc:h2:mem:testdb
    driverClassname: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:             # tell Spring which profile to activate. The name is derived and know to Spring
    active: "prod"        # since the convention of 'application-{profileName}' was followed. Now it takes from configserver.
 # config:                This property tells Spring to import the values in the files specified. This is needed
 #   import:                        in case the naming convention of "application-{profile}" is not followed.
 #     - "application_qa.yml"       Spring ignores .properties/yml files that do not follow the convention other
 #     - "application_prod.yml"     than the default file.
  config:
    import: "optional:configserver:http://localhost:8071/"  # adding 'optional' since this value does not get overridden when another value is passed as an environment variable. Apparently this one property in spring does not use the highest precedence value, but evaluates are values for spring.config.import. Since this is running in a container, it cannot reach configserver via localhost hence optional.
      # telling accounts service to import configs from the configserver
                                                   # at that location. The string 'configserver' is mandatory here irrespective of server application name.
#  rabbitmq:              # define broker credentials for RabbitMQ (container running on port 5672) to use. Commenting out since not used going forward.
#    host: localhost      # 'busrefresh' endpoint of actuator for Spring Cloud Bus. These are default values
#    port: 5672           # and do not need to be mentioned explicitly since Spring Cloud is already configured
#    username: guest      # Instead of invoking 'actuator/refresh' for each service, 'actuator/busrefresh' can
#    password: guest      # be invoked for one service and all nodes registered with MQ will refresh configs from configserver
                         # via Spring Cloud Bus

build:
  version: "1.0"

# adding some properties with the prefix 'accounts' to demonstrate @ConfigurationProperties of Spring Boot to inject
# external values at runtime. Here 'message' is a String value. 'contactInfo' is a Map of <String, String> values,
# and 'onCallSupport' is a List of <String> values.

accounts:
  message: "Welcome to Accounts service of DemoBank!"
  contactInfo:
    name: "John Doe"
    email: "john@demobank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 512-5678

# expose all management related endpoints support by Spring Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"