# changed application.properties to application.yml (YAML file)

server:
  port: 8080

spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassname: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:             # tell Spring which profile to activate. The name is derived and know to Spring
    active: "prod"        # since the convention of 'application-{profileName}' was followed. Now it takes from configserver.
 # config:                This property tells Spring to import the values in the files specified. This is needed
 #   import:                        in case the naming convention of "application-{profile}" is not followed.
 #     - "application_qa.yml"       Spring ignores .properties/yml files that do not follow the convention other
 #     - "application_prod.yml"     than the default file.
  config:
    import: "configserver:http://localhost:8071/"  # telling accounts service to import configs from the configserver
                                                   # at that location. The string 'configserver' is mandatory here irrespective of server application name.

build:
  version: "1.0"

# adding some properties with the prefix 'accounts' to demonstrate @ConfigurationProperties of Spring Boot to inject
# external values at runtime. Here 'message' is a String value. 'contactInfo' is a Map of <String, String> values,
# and 'onCallSupport' is a List of <String> values.

accounts:
  message: "Welcome to Accounts service of DemoBank!"
  contactInfo:
    name: "John Doe"
    email: "john@demobank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 512-5678