# adding a separate docker compose file for each profile to handle running of configserver + services for that profile.
services:
#  commented out rabbit service since RabbitMQ is unused going forward.
#  rabbit:                               # define a service named 'rabbit' to perform a health check on rabbitmq
#    image: rabbitmq:4-management        # container since it is a dependency for configserver container. This
#    hostname: rabbitmq                  # also runs in the same network as the rest to be accessible to each other
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    healthcheck:
#      test: rabbitmq-diagnostics check_port_connectivity
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 5s
#    extends:                            # importing common config from common-config.yml file with 'extends'
#      file: common-config.yml
#      service: network-deploy-service

# Commeting out MySQL containers for each service as they have been moved back to H2 database.
#  accountsdb:                            # creating a service for the new MySQL container for Accounts service and so on
#    container_name: accountsdb
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_DATABASE: accountsdb
#    extends:
#      file: common-config.yml
#      service: microservice-db-config
#
#  cardsdb:
#    container_name: cardsdb
#    ports:
#      - "3308:3306"
#    environment:
#      MYSQL_DATABASE: cardsdb
#    extends:
#      file: common-config.yml
#      service: microservice-db-config
#
#  loansdb:
#    container_name: loansdb
#    ports:
#      - "3307:3306"
#    environment:
#      MYSQL_DATABASE: loansdb
#    extends:
#      file: common-config.yml
#      service: microservice-db-config

  redis:                                # add a service for Redis datastore container. For Redis request rateLimiter
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL","redis-cli ping | grep PONG"]
      timeout: 10s
      retries: 10
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:                         # adding configserver as a service with the same name to run in the
    image: "demobank/configserver:s6"   # network 'demobank' to allow the containers to communicate with each other
    container_name: "configserver-ms"   # by name since each container has its own isolated namespace/loopback
    ports:                              # for 'localhost'. If accounts container is running outside a network,
      - "8071:8071"                     # it won't be able to find configserver at localhost:8071 since accounts
                                        # container has its own 'localhost' and nothing is listening on 8071.

    healthcheck:              # add a health check with instruction on what to test for. This one checks for readiness of configserver container
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s           # instruct the health check to start only 10s after the container starts, to perform
      retries: 10             # up to 10 retries, with an interval of 10s between each. If the check takes longer
      timeout: 5s             # than 5s from the time it started, it is considered to have failed.
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:               # adding eurekaserver as a service with the same name to run in the
    image: "demobank/eurekaserver:s8"
    container_name: "eurekaserver-ms"
    ports:
      - "8070:8070"
    healthcheck:              # same health check as configserver but using the port number for eurekaserver
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      retries: 10
      timeout: 5s
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  accounts:
    image: "demobank/accounts:s10"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    environment:                       # defining environment variables to allow comms with configserver as mentioned above
      SPRING_APPLICATION_NAME: "accounts"
      #SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb" not needed after moving back to H2 db
    healthcheck:              # add health check for accounts so it can be used as a dependency for gatewayserver
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      retries: 10
      timeout: 5s
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  cards:
    image: "demobank/cards:s9"
    container_name: "cards-ms"
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: cards
      #SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"  # mysql listens on intenal container port 3306 and not exposed host port
    healthcheck:              # add health check so it can be used as a dependency for gatewayserver
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      retries: 10
      timeout: 5s
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  loans:
    image: "demobank/loans:s9"
    container_name: "loans-ms"
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: loans
      #SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    healthcheck:              # add health check so it can be used as a dependency for gatewayserver
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      retries: 10
      timeout: 5s
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  # add a new service for GatewayServer container. It will be created only after accounts, cards, and loans services pass their health checks
  gatewayserver:
    image: "demobank/gatewayserver:s10"
    container_name: "gatewayserver-ms"
    ports:
      - "8072:8072"
    depends_on:
      accounts:
        condition: service_healthy
      cards:
        condition: service_healthy
      loans:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_DATA_REDIS_HOST: redis
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

networks:
  demobank:
    driver: "bridge"